/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v2.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v2.Keys;
import org.jooq.example.migrator.model.v2.tables.records.v2_AuthorRecord;
import org.jooq.example.migrator.model.v2.v2_FlywayTest;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_2"
    },
    date = "2017-05-14T20:59:56.850Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v2_Author extends TableImpl<v2_AuthorRecord> {

    private static final long serialVersionUID = 1320409346;

    /**
     * The reference instance of <code>FLYWAY_TEST.AUTHOR</code>
     */
    public static final v2_Author v2_AUTHOR = new v2_Author();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<v2_AuthorRecord> getRecordType() {
        return v2_AuthorRecord.class;
    }

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.ID</code>.
     */
    public final TableField<v2_AuthorRecord, Integer> v2_ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.FIRST_NAME</code>.
     */
    public final TableField<v2_AuthorRecord, String> v2_FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.LAST_NAME</code>.
     */
    public final TableField<v2_AuthorRecord, String> v2_LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.DATE_OF_BIRTH</code>.
     */
    public final TableField<v2_AuthorRecord, Date> v2_DATE_OF_BIRTH = createField("DATE_OF_BIRTH", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.YEAR_OF_BIRTH</code>.
     */
    public final TableField<v2_AuthorRecord, Integer> v2_YEAR_OF_BIRTH = createField("YEAR_OF_BIRTH", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.ADDRESS</code>.
     */
    public final TableField<v2_AuthorRecord, String> v2_ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * Create a <code>FLYWAY_TEST.AUTHOR</code> table reference
     */
    public v2_Author() {
        this("AUTHOR", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.AUTHOR</code> table reference
     */
    public v2_Author(String alias) {
        this(alias, v2_AUTHOR);
    }

    private v2_Author(String alias, Table<v2_AuthorRecord> aliased) {
        this(alias, aliased, null);
    }

    private v2_Author(String alias, Table<v2_AuthorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return v2_FlywayTest.v2_FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<v2_AuthorRecord> getPrimaryKey() {
        return Keys.v2_PK_T_AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<v2_AuthorRecord>> getKeys() {
        return Arrays.<UniqueKey<v2_AuthorRecord>>asList(Keys.v2_PK_T_AUTHOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public v2_Author as(String alias) {
        return new v2_Author(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public v2_Author rename(String name) {
        return new v2_Author(name, null);
    }
}
