/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v2.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v2.Keys;
import org.jooq.example.migrator.model.v2.tables.records.v2_BookRecord;
import org.jooq.example.migrator.model.v2.v2_FlywayTest;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_2"
    },
    date = "2017-05-14T20:59:56.850Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v2_Book extends TableImpl<v2_BookRecord> {

    private static final long serialVersionUID = -2044346137;

    /**
     * The reference instance of <code>FLYWAY_TEST.BOOK</code>
     */
    public static final v2_Book v2_BOOK = new v2_Book();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<v2_BookRecord> getRecordType() {
        return v2_BookRecord.class;
    }

    /**
     * The column <code>FLYWAY_TEST.BOOK.ID</code>.
     */
    public final TableField<v2_BookRecord, Integer> v2_ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.BOOK.AUTHOR_ID</code>.
     */
    public final TableField<v2_BookRecord, Integer> v2_AUTHOR_ID = createField("AUTHOR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.BOOK.TITLE</code>.
     */
    public final TableField<v2_BookRecord, String> v2_TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

    /**
     * Create a <code>FLYWAY_TEST.BOOK</code> table reference
     */
    public v2_Book() {
        this("BOOK", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.BOOK</code> table reference
     */
    public v2_Book(String alias) {
        this(alias, v2_BOOK);
    }

    private v2_Book(String alias, Table<v2_BookRecord> aliased) {
        this(alias, aliased, null);
    }

    private v2_Book(String alias, Table<v2_BookRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return v2_FlywayTest.v2_FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<v2_BookRecord> getPrimaryKey() {
        return Keys.v2_PK_T_BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<v2_BookRecord>> getKeys() {
        return Arrays.<UniqueKey<v2_BookRecord>>asList(Keys.v2_PK_T_BOOK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<v2_BookRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<v2_BookRecord, ?>>asList(Keys.v2_FK_T_BOOK_AUTHOR_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public v2_Book as(String alias) {
        return new v2_Book(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public v2_Book rename(String name) {
        return new v2_Book(name, null);
    }
}
