/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v1.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v1.FlywayTest;
import org.jooq.example.migrator.model.v1.Keys;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_1"
    },
    date = "2017-05-03T20:59:30.778Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v1_AUTHOR extends TableImpl<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR> {

    private static final long serialVersionUID = 452588082;

    /**
     * The reference instance of <code>FLYWAY_TEST.AUTHOR</code>
     */
    public static final v1_AUTHOR v1_AUTHOR = new v1_AUTHOR();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR> getRecordType() {
        return org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR.class;
    }

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.ID</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.FIRST_NAME</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR, String> FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.LAST_NAME</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR, String> LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.DATE_OF_BIRTH</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR, Date> DATE_OF_BIRTH = createField("DATE_OF_BIRTH", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.YEAR_OF_BIRTH</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR, Integer> YEAR_OF_BIRTH = createField("YEAR_OF_BIRTH", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.ADDRESS</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR, String> ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * Create a <code>FLYWAY_TEST.AUTHOR</code> table reference
     */
    public v1_AUTHOR() {
        this("AUTHOR", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.AUTHOR</code> table reference
     */
    public v1_AUTHOR(String alias) {
        this(alias, v1_AUTHOR);
    }

    private v1_AUTHOR(String alias, Table<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR> aliased) {
        this(alias, aliased, null);
    }

    private v1_AUTHOR(String alias, Table<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return FlywayTest.FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR> getPrimaryKey() {
        return Keys.PK_T_AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR>> getKeys() {
        return Arrays.<UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR>>asList(Keys.PK_T_AUTHOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public v1_AUTHOR as(String alias) {
        return new v1_AUTHOR(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public v1_AUTHOR rename(String name) {
        return new v1_AUTHOR(name, null);
    }
}
