/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v1.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v1.Keys;
import org.jooq.example.migrator.model.v1.tables.records.v1_AuthorRecord;
import org.jooq.example.migrator.model.v1.v1_FlywayTest;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:null"
    },
    date = "2017-05-16T21:33:40.187Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v1_Author extends TableImpl<v1_AuthorRecord> {

    private static final long serialVersionUID = -1601006275;

    /**
     * The reference instance of <code>FLYWAY_TEST.AUTHOR</code>
     */
    public static final v1_Author v1_AUTHOR = new v1_Author();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<v1_AuthorRecord> getRecordType() {
        return v1_AuthorRecord.class;
    }

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.ID</code>.
     */
    public final TableField<v1_AuthorRecord, Integer> v1_ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.FIRST_NAME</code>.
     */
    public final TableField<v1_AuthorRecord, String> v1_FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.LAST_NAME</code>.
     */
    public final TableField<v1_AuthorRecord, String> v1_LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.DATE_OF_BIRTH</code>.
     */
    public final TableField<v1_AuthorRecord, Date> v1_DATE_OF_BIRTH = createField("DATE_OF_BIRTH", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.YEAR_OF_BIRTH</code>.
     */
    public final TableField<v1_AuthorRecord, Integer> v1_YEAR_OF_BIRTH = createField("YEAR_OF_BIRTH", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.ADDRESS</code>.
     */
    public final TableField<v1_AuthorRecord, String> v1_ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * Create a <code>FLYWAY_TEST.AUTHOR</code> table reference
     */
    public v1_Author() {
        this("AUTHOR", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.AUTHOR</code> table reference
     */
    public v1_Author(String alias) {
        this(alias, v1_AUTHOR);
    }

    private v1_Author(String alias, Table<v1_AuthorRecord> aliased) {
        this(alias, aliased, null);
    }

    private v1_Author(String alias, Table<v1_AuthorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return v1_FlywayTest.v1_FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<v1_AuthorRecord> getPrimaryKey() {
        return Keys.v1_PK_T_AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<v1_AuthorRecord>> getKeys() {
        return Arrays.<UniqueKey<v1_AuthorRecord>>asList(Keys.v1_PK_T_AUTHOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public v1_Author as(String alias) {
        return new v1_Author(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public v1_Author rename(String name) {
        return new v1_Author(name, null);
    }
}
