/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v1.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v1.FlywayTest;
import org.jooq.example.migrator.model.v1.Keys;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_1"
    },
    date = "2017-05-03T20:59:30.778Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v1_BOOK extends TableImpl<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK> {

    private static final long serialVersionUID = -85364282;

    /**
     * The reference instance of <code>FLYWAY_TEST.BOOK</code>
     */
    public static final v1_BOOK v1_BOOK = new v1_BOOK();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK> getRecordType() {
        return org.jooq.example.migrator.model.v1.tables.records.v1_BOOK.class;
    }

    /**
     * The column <code>FLYWAY_TEST.BOOK.ID</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.BOOK.AUTHOR_ID</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK, Integer> AUTHOR_ID = createField("AUTHOR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.BOOK.TITLE</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK, String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

    /**
     * Create a <code>FLYWAY_TEST.BOOK</code> table reference
     */
    public v1_BOOK() {
        this("BOOK", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.BOOK</code> table reference
     */
    public v1_BOOK(String alias) {
        this(alias, v1_BOOK);
    }

    private v1_BOOK(String alias, Table<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK> aliased) {
        this(alias, aliased, null);
    }

    private v1_BOOK(String alias, Table<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return FlywayTest.FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK> getPrimaryKey() {
        return Keys.PK_T_BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK>> getKeys() {
        return Arrays.<UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK>>asList(Keys.PK_T_BOOK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK, ?>> getReferences() {
        return Arrays.<ForeignKey<org.jooq.example.migrator.model.v1.tables.records.v1_BOOK, ?>>asList(Keys.FK_T_BOOK_AUTHOR_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public v1_BOOK as(String alias) {
        return new v1_BOOK(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public v1_BOOK rename(String name) {
        return new v1_BOOK(name, null);
    }
}
