/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v1.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v1.FlywayTest;
import org.jooq.example.migrator.model.v1.Keys;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_1"
    },
    date = "2017-05-03T20:59:30.778Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v1_schema_version extends TableImpl<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version> {

    private static final long serialVersionUID = -1275692977;

    /**
     * The reference instance of <code>FLYWAY_TEST.schema_version</code>
     */
    public static final v1_schema_version v1_schema_version = new v1_schema_version();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version> getRecordType() {
        return org.jooq.example.migrator.model.v1.tables.records.v1_schema_version.class;
    }

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_rank</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, Integer> INSTALLED_RANK = createField("installed_rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.version</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.description</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.type</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.script</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, String> SCRIPT = createField("script", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.checksum</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, Integer> CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_by</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, String> INSTALLED_BY = createField("installed_by", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_on</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, Timestamp> INSTALLED_ON = createField("installed_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.execution_time</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, Integer> EXECUTION_TIME = createField("execution_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.success</code>.
     */
    public final TableField<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version, Boolean> SUCCESS = createField("success", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>FLYWAY_TEST.schema_version</code> table reference
     */
    public v1_schema_version() {
        this("schema_version", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.schema_version</code> table reference
     */
    public v1_schema_version(String alias) {
        this(alias, v1_schema_version);
    }

    private v1_schema_version(String alias, Table<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version> aliased) {
        this(alias, aliased, null);
    }

    private v1_schema_version(String alias, Table<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return FlywayTest.FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version> getPrimaryKey() {
        return Keys.SCHEMA_VERSION_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version>> getKeys() {
        return Arrays.<UniqueKey<org.jooq.example.migrator.model.v1.tables.records.v1_schema_version>>asList(Keys.SCHEMA_VERSION_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public v1_schema_version as(String alias) {
        return new v1_schema_version(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public v1_schema_version rename(String name) {
        return new v1_schema_version(name, null);
    }
}
