/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.app.model.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.app.model.Keys;
import org.jooq.example.app.model.null_FlywayTest;
import org.jooq.example.app.model.tables.records.null_AuthorRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_3"
    },
    date = "2017-05-11T21:47:26.351Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class null_Author extends TableImpl<null_AuthorRecord> {

    private static final long serialVersionUID = -821034742;

    /**
     * The reference instance of <code>FLYWAY_TEST.AUTHOR</code>
     */
    public static final null_Author null_AUTHOR = new null_Author();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<null_AuthorRecord> getRecordType() {
        return null_AuthorRecord.class;
    }

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.ID</code>.
     */
    public final TableField<null_AuthorRecord, Integer> null_ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.FIRST_NAME</code>.
     */
    public final TableField<null_AuthorRecord, String> null_FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.LAST_NAME</code>.
     */
    public final TableField<null_AuthorRecord, String> null_LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.DATE_OF_BIRTH</code>.
     */
    public final TableField<null_AuthorRecord, Date> null_DATE_OF_BIRTH = createField("DATE_OF_BIRTH", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.YEAR_OF_BIRTH</code>.
     */
    public final TableField<null_AuthorRecord, Integer> null_YEAR_OF_BIRTH = createField("YEAR_OF_BIRTH", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.ADDRESS</code>.
     */
    public final TableField<null_AuthorRecord, String> null_ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>FLYWAY_TEST.AUTHOR.GENDER</code>.
     */
    public final TableField<null_AuthorRecord, Integer> null_GENDER = createField("GENDER", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>FLYWAY_TEST.AUTHOR</code> table reference
     */
    public null_Author() {
        this("AUTHOR", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.AUTHOR</code> table reference
     */
    public null_Author(String alias) {
        this(alias, null_AUTHOR);
    }

    private null_Author(String alias, Table<null_AuthorRecord> aliased) {
        this(alias, aliased, null);
    }

    private null_Author(String alias, Table<null_AuthorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null_FlywayTest.null_FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<null_AuthorRecord> getPrimaryKey() {
        return Keys.null_PK_T_AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<null_AuthorRecord>> getKeys() {
        return Arrays.<UniqueKey<null_AuthorRecord>>asList(Keys.null_PK_T_AUTHOR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public null_Author as(String alias) {
        return new null_Author(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public null_Author rename(String name) {
        return new null_Author(name, null);
    }
}
