/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.app.model.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.app.model.Keys;
import org.jooq.example.app.model.null_FlywayTest;
import org.jooq.example.app.model.tables.records.null_SchemaVersionRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_3"
    },
    date = "2017-05-11T21:47:26.351Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class null_SchemaVersion extends TableImpl<null_SchemaVersionRecord> {

    private static final long serialVersionUID = 55242506;

    /**
     * The reference instance of <code>FLYWAY_TEST.schema_version</code>
     */
    public static final null_SchemaVersion null_SCHEMA_VERSION = new null_SchemaVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<null_SchemaVersionRecord> getRecordType() {
        return null_SchemaVersionRecord.class;
    }

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_rank</code>.
     */
    public final TableField<null_SchemaVersionRecord, Integer> null_INSTALLED_RANK = createField("installed_rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.version</code>.
     */
    public final TableField<null_SchemaVersionRecord, String> null_VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.description</code>.
     */
    public final TableField<null_SchemaVersionRecord, String> null_DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.type</code>.
     */
    public final TableField<null_SchemaVersionRecord, String> null_TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.script</code>.
     */
    public final TableField<null_SchemaVersionRecord, String> null_SCRIPT = createField("script", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.checksum</code>.
     */
    public final TableField<null_SchemaVersionRecord, Integer> null_CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_by</code>.
     */
    public final TableField<null_SchemaVersionRecord, String> null_INSTALLED_BY = createField("installed_by", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_on</code>.
     */
    public final TableField<null_SchemaVersionRecord, Timestamp> null_INSTALLED_ON = createField("installed_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.execution_time</code>.
     */
    public final TableField<null_SchemaVersionRecord, Integer> null_EXECUTION_TIME = createField("execution_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.success</code>.
     */
    public final TableField<null_SchemaVersionRecord, Boolean> null_SUCCESS = createField("success", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>FLYWAY_TEST.schema_version</code> table reference
     */
    public null_SchemaVersion() {
        this("schema_version", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.schema_version</code> table reference
     */
    public null_SchemaVersion(String alias) {
        this(alias, null_SCHEMA_VERSION);
    }

    private null_SchemaVersion(String alias, Table<null_SchemaVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private null_SchemaVersion(String alias, Table<null_SchemaVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null_FlywayTest.null_FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<null_SchemaVersionRecord> getPrimaryKey() {
        return Keys.null_SCHEMA_VERSION_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<null_SchemaVersionRecord>> getKeys() {
        return Arrays.<UniqueKey<null_SchemaVersionRecord>>asList(Keys.null_SCHEMA_VERSION_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public null_SchemaVersion as(String alias) {
        return new null_SchemaVersion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public null_SchemaVersion rename(String name) {
        return new null_SchemaVersion(name, null);
    }
}
