/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.app.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.app.model.Keys;
import org.jooq.example.app.model.null_FlywayTest;
import org.jooq.example.app.model.tables.records.null_BookRecord;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_3"
    },
    date = "2017-05-11T21:47:26.351Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class null_Book extends TableImpl<null_BookRecord> {

    private static final long serialVersionUID = 1615678468;

    /**
     * The reference instance of <code>FLYWAY_TEST.BOOK</code>
     */
    public static final null_Book null_BOOK = new null_Book();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<null_BookRecord> getRecordType() {
        return null_BookRecord.class;
    }

    /**
     * The column <code>FLYWAY_TEST.BOOK.ID</code>.
     */
    public final TableField<null_BookRecord, Integer> null_ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.BOOK.AUTHOR_ID</code>.
     */
    public final TableField<null_BookRecord, Integer> null_AUTHOR_ID = createField("AUTHOR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.BOOK.TITLE</code>.
     */
    public final TableField<null_BookRecord, String> null_TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

    /**
     * Create a <code>FLYWAY_TEST.BOOK</code> table reference
     */
    public null_Book() {
        this("BOOK", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.BOOK</code> table reference
     */
    public null_Book(String alias) {
        this(alias, null_BOOK);
    }

    private null_Book(String alias, Table<null_BookRecord> aliased) {
        this(alias, aliased, null);
    }

    private null_Book(String alias, Table<null_BookRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null_FlywayTest.null_FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<null_BookRecord> getPrimaryKey() {
        return Keys.null_PK_T_BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<null_BookRecord>> getKeys() {
        return Arrays.<UniqueKey<null_BookRecord>>asList(Keys.null_PK_T_BOOK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<null_BookRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<null_BookRecord, ?>>asList(Keys.null_FK_T_BOOK_AUTHOR_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public null_Book as(String alias) {
        return new null_Book(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public null_Book rename(String name) {
        return new null_Book(name, null);
    }
}
