/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v2;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v2.tables.records.v2_AuthorRecord;
import org.jooq.example.migrator.model.v2.tables.records.v2_BookRecord;
import org.jooq.example.migrator.model.v2.tables.records.v2_SchemaVersionRecord;
import org.jooq.example.migrator.model.v2.tables.v2_Author;
import org.jooq.example.migrator.model.v2.tables.v2_Book;
import org.jooq.example.migrator.model.v2.tables.v2_SchemaVersion;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>FLYWAY_TEST</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_2"
    },
    date = "2017-05-14T20:59:56.850Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<v2_AuthorRecord> v2_PK_T_AUTHOR = UniqueKeys0.v2_PK_T_AUTHOR;
    public static final UniqueKey<v2_BookRecord> v2_PK_T_BOOK = UniqueKeys0.v2_PK_T_BOOK;
    public static final UniqueKey<v2_SchemaVersionRecord> v2_SCHEMA_VERSION_PK = UniqueKeys0.v2_SCHEMA_VERSION_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<v2_BookRecord, v2_AuthorRecord> v2_FK_T_BOOK_AUTHOR_ID = ForeignKeys0.v2_FK_T_BOOK_AUTHOR_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<v2_AuthorRecord> v2_PK_T_AUTHOR = createUniqueKey(v2_Author.v2_AUTHOR, "PK_T_AUTHOR", v2_Author.v2_AUTHOR.v2_ID);
        public static final UniqueKey<v2_BookRecord> v2_PK_T_BOOK = createUniqueKey(v2_Book.v2_BOOK, "PK_T_BOOK", v2_Book.v2_BOOK.v2_ID);
        public static final UniqueKey<v2_SchemaVersionRecord> v2_SCHEMA_VERSION_PK = createUniqueKey(v2_SchemaVersion.v2_SCHEMA_VERSION, "schema_version_pk", v2_SchemaVersion.v2_SCHEMA_VERSION.v2_INSTALLED_RANK);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<v2_BookRecord, v2_AuthorRecord> v2_FK_T_BOOK_AUTHOR_ID = createForeignKey(org.jooq.example.migrator.model.v2.Keys.v2_PK_T_AUTHOR, v2_Book.v2_BOOK, "FK_T_BOOK_AUTHOR_ID", v2_Book.v2_BOOK.v2_AUTHOR_ID);
    }
}
