/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v3;


import javax.annotation.Generated;

import org.jooq.example.migrator.model.v3.tables.v3_Author;
import org.jooq.example.migrator.model.v3.tables.v3_Book;
import org.jooq.example.migrator.model.v3.tables.v3_SchemaVersion;


/**
 * Convenience access to all tables in FLYWAY_TEST
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_2"
    },
    date = "2017-05-16T21:33:40.682Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>FLYWAY_TEST.AUTHOR</code>.
     */
    public static final v3_Author v3_AUTHOR = org.jooq.example.migrator.model.v3.tables.v3_Author.v3_AUTHOR;

    /**
     * The table <code>FLYWAY_TEST.BOOK</code>.
     */
    public static final v3_Book v3_BOOK = org.jooq.example.migrator.model.v3.tables.v3_Book.v3_BOOK;

    /**
     * The table <code>FLYWAY_TEST.schema_version</code>.
     */
    public static final v3_SchemaVersion v3_SCHEMA_VERSION = org.jooq.example.migrator.model.v3.tables.v3_SchemaVersion.v3_SCHEMA_VERSION;
}
