/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v3.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v3.Keys;
import org.jooq.example.migrator.model.v3.tables.records.v3_BookRecord;
import org.jooq.example.migrator.model.v3.v3_FlywayTest;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_2"
    },
    date = "2017-05-16T21:33:40.682Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v3_Book extends TableImpl<v3_BookRecord> {

    private static final long serialVersionUID = 1207081438;

    /**
     * The reference instance of <code>FLYWAY_TEST.BOOK</code>
     */
    public static final v3_Book v3_BOOK = new v3_Book();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<v3_BookRecord> getRecordType() {
        return v3_BookRecord.class;
    }

    /**
     * The column <code>FLYWAY_TEST.BOOK.ID</code>.
     */
    public final TableField<v3_BookRecord, Integer> v3_ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.BOOK.AUTHOR_ID</code>.
     */
    public final TableField<v3_BookRecord, Integer> v3_AUTHOR_ID = createField("AUTHOR_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.BOOK.TITLE</code>.
     */
    public final TableField<v3_BookRecord, String> v3_TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

    /**
     * Create a <code>FLYWAY_TEST.BOOK</code> table reference
     */
    public v3_Book() {
        this("BOOK", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.BOOK</code> table reference
     */
    public v3_Book(String alias) {
        this(alias, v3_BOOK);
    }

    private v3_Book(String alias, Table<v3_BookRecord> aliased) {
        this(alias, aliased, null);
    }

    private v3_Book(String alias, Table<v3_BookRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return v3_FlywayTest.v3_FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<v3_BookRecord> getPrimaryKey() {
        return Keys.v3_PK_T_BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<v3_BookRecord>> getKeys() {
        return Arrays.<UniqueKey<v3_BookRecord>>asList(Keys.v3_PK_T_BOOK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<v3_BookRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<v3_BookRecord, ?>>asList(Keys.v3_FK_T_BOOK_AUTHOR_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public v3_Book as(String alias) {
        return new v3_Book(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public v3_Book rename(String name) {
        return new v3_Book(name, null);
    }
}
