/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v3.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v3.Keys;
import org.jooq.example.migrator.model.v3.tables.records.v3_SchemaVersionRecord;
import org.jooq.example.migrator.model.v3.v3_FlywayTest;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_2"
    },
    date = "2017-05-16T21:33:40.682Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v3_SchemaVersion extends TableImpl<v3_SchemaVersionRecord> {

    private static final long serialVersionUID = -1957822748;

    /**
     * The reference instance of <code>FLYWAY_TEST.schema_version</code>
     */
    public static final v3_SchemaVersion v3_SCHEMA_VERSION = new v3_SchemaVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<v3_SchemaVersionRecord> getRecordType() {
        return v3_SchemaVersionRecord.class;
    }

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_rank</code>.
     */
    public final TableField<v3_SchemaVersionRecord, Integer> v3_INSTALLED_RANK = createField("installed_rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.version</code>.
     */
    public final TableField<v3_SchemaVersionRecord, String> v3_VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.description</code>.
     */
    public final TableField<v3_SchemaVersionRecord, String> v3_DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.type</code>.
     */
    public final TableField<v3_SchemaVersionRecord, String> v3_TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.script</code>.
     */
    public final TableField<v3_SchemaVersionRecord, String> v3_SCRIPT = createField("script", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.checksum</code>.
     */
    public final TableField<v3_SchemaVersionRecord, Integer> v3_CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_by</code>.
     */
    public final TableField<v3_SchemaVersionRecord, String> v3_INSTALLED_BY = createField("installed_by", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.installed_on</code>.
     */
    public final TableField<v3_SchemaVersionRecord, Timestamp> v3_INSTALLED_ON = createField("installed_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.execution_time</code>.
     */
    public final TableField<v3_SchemaVersionRecord, Integer> v3_EXECUTION_TIME = createField("execution_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>FLYWAY_TEST.schema_version.success</code>.
     */
    public final TableField<v3_SchemaVersionRecord, Boolean> v3_SUCCESS = createField("success", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a <code>FLYWAY_TEST.schema_version</code> table reference
     */
    public v3_SchemaVersion() {
        this("schema_version", null);
    }

    /**
     * Create an aliased <code>FLYWAY_TEST.schema_version</code> table reference
     */
    public v3_SchemaVersion(String alias) {
        this(alias, v3_SCHEMA_VERSION);
    }

    private v3_SchemaVersion(String alias, Table<v3_SchemaVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private v3_SchemaVersion(String alias, Table<v3_SchemaVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return v3_FlywayTest.v3_FLYWAY_TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<v3_SchemaVersionRecord> getPrimaryKey() {
        return Keys.v3_SCHEMA_VERSION_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<v3_SchemaVersionRecord>> getKeys() {
        return Arrays.<UniqueKey<v3_SchemaVersionRecord>>asList(Keys.v3_SCHEMA_VERSION_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public v3_SchemaVersion as(String alias) {
        return new v3_SchemaVersion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public v3_SchemaVersion rename(String name) {
        return new v3_SchemaVersion(name, null);
    }
}
