/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.app.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.example.app.model.tables.null_Author;
import org.jooq.example.app.model.tables.null_Book;
import org.jooq.example.app.model.tables.null_SchemaVersion;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_3"
    },
    date = "2017-05-11T21:47:26.351Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class null_FlywayTest extends SchemaImpl {

    private static final long serialVersionUID = -802822438;

    /**
     * The reference instance of <code>FLYWAY_TEST</code>
     */
    public static final null_FlywayTest null_FLYWAY_TEST = new null_FlywayTest();

    /**
     * The table <code>FLYWAY_TEST.AUTHOR</code>.
     */
    public final null_Author null_AUTHOR = org.jooq.example.app.model.tables.null_Author.null_AUTHOR;

    /**
     * The table <code>FLYWAY_TEST.BOOK</code>.
     */
    public final null_Book null_BOOK = org.jooq.example.app.model.tables.null_Book.null_BOOK;

    /**
     * The table <code>FLYWAY_TEST.schema_version</code>.
     */
    public final null_SchemaVersion null_SCHEMA_VERSION = org.jooq.example.app.model.tables.null_SchemaVersion.null_SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private null_FlywayTest() {
        super("FLYWAY_TEST", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.null_S_AUTHOR_ID);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            null_Author.null_AUTHOR,
            null_Book.null_BOOK,
            null_SchemaVersion.null_SCHEMA_VERSION);
    }
}
