/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.app.model;


import javax.annotation.Generated;

import org.jooq.example.app.model.tables.null_Author;
import org.jooq.example.app.model.tables.null_Book;
import org.jooq.example.app.model.tables.null_SchemaVersion;


/**
 * Convenience access to all tables in FLYWAY_TEST
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_3"
    },
    date = "2017-05-11T21:47:26.351Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>FLYWAY_TEST.AUTHOR</code>.
     */
    public static final null_Author null_AUTHOR = org.jooq.example.app.model.tables.null_Author.null_AUTHOR;

    /**
     * The table <code>FLYWAY_TEST.BOOK</code>.
     */
    public static final null_Book null_BOOK = org.jooq.example.app.model.tables.null_Book.null_BOOK;

    /**
     * The table <code>FLYWAY_TEST.schema_version</code>.
     */
    public static final null_SchemaVersion null_SCHEMA_VERSION = org.jooq.example.app.model.tables.null_SchemaVersion.null_SCHEMA_VERSION;
}
