/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v1;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v1.tables.records.v1_AuthorRecord;
import org.jooq.example.migrator.model.v1.tables.records.v1_BookRecord;
import org.jooq.example.migrator.model.v1.tables.records.v1_SchemaVersionRecord;
import org.jooq.example.migrator.model.v1.tables.v1_Author;
import org.jooq.example.migrator.model.v1.tables.v1_Book;
import org.jooq.example.migrator.model.v1.tables.v1_SchemaVersion;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>FLYWAY_TEST</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_1"
    },
    date = "2017-05-14T20:58:47.177Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<v1_AuthorRecord> v1_PK_T_AUTHOR = UniqueKeys0.v1_PK_T_AUTHOR;
    public static final UniqueKey<v1_BookRecord> v1_PK_T_BOOK = UniqueKeys0.v1_PK_T_BOOK;
    public static final UniqueKey<v1_SchemaVersionRecord> v1_SCHEMA_VERSION_PK = UniqueKeys0.v1_SCHEMA_VERSION_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<v1_BookRecord, v1_AuthorRecord> v1_FK_T_BOOK_AUTHOR_ID = ForeignKeys0.v1_FK_T_BOOK_AUTHOR_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<v1_AuthorRecord> v1_PK_T_AUTHOR = createUniqueKey(v1_Author.v1_AUTHOR, "PK_T_AUTHOR", v1_Author.v1_AUTHOR.v1_ID);
        public static final UniqueKey<v1_BookRecord> v1_PK_T_BOOK = createUniqueKey(v1_Book.v1_BOOK, "PK_T_BOOK", v1_Book.v1_BOOK.v1_ID);
        public static final UniqueKey<v1_SchemaVersionRecord> v1_SCHEMA_VERSION_PK = createUniqueKey(v1_SchemaVersion.v1_SCHEMA_VERSION, "schema_version_pk", v1_SchemaVersion.v1_SCHEMA_VERSION.v1_INSTALLED_RANK);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<v1_BookRecord, v1_AuthorRecord> v1_FK_T_BOOK_AUTHOR_ID = createForeignKey(org.jooq.example.migrator.model.v1.Keys.v1_PK_T_AUTHOR, v1_Book.v1_BOOK, "FK_T_BOOK_AUTHOR_ID", v1_Book.v1_BOOK.v1_AUTHOR_ID);
    }
}
