/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v1;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.example.migrator.model.v1.tables.records.v1_AUTHOR;
import org.jooq.example.migrator.model.v1.tables.records.v1_BOOK;
import org.jooq.example.migrator.model.v1.tables.records.v1_schema_version;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>FLYWAY_TEST</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_1"
    },
    date = "2017-05-03T20:59:30.778Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<v1_AUTHOR> PK_T_AUTHOR = UniqueKeys0.PK_T_AUTHOR;
    public static final UniqueKey<v1_BOOK> PK_T_BOOK = UniqueKeys0.PK_T_BOOK;
    public static final UniqueKey<v1_schema_version> SCHEMA_VERSION_PK = UniqueKeys0.SCHEMA_VERSION_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<v1_BOOK, v1_AUTHOR> FK_T_BOOK_AUTHOR_ID = ForeignKeys0.FK_T_BOOK_AUTHOR_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<v1_AUTHOR> PK_T_AUTHOR = createUniqueKey(org.jooq.example.migrator.model.v1.tables.v1_AUTHOR.v1_AUTHOR, "PK_T_AUTHOR", org.jooq.example.migrator.model.v1.tables.v1_AUTHOR.v1_AUTHOR.ID);
        public static final UniqueKey<v1_BOOK> PK_T_BOOK = createUniqueKey(org.jooq.example.migrator.model.v1.tables.v1_BOOK.v1_BOOK, "PK_T_BOOK", org.jooq.example.migrator.model.v1.tables.v1_BOOK.v1_BOOK.ID);
        public static final UniqueKey<v1_schema_version> SCHEMA_VERSION_PK = createUniqueKey(org.jooq.example.migrator.model.v1.tables.v1_schema_version.v1_schema_version, "schema_version_pk", org.jooq.example.migrator.model.v1.tables.v1_schema_version.v1_schema_version.INSTALLED_RANK);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<v1_BOOK, v1_AUTHOR> FK_T_BOOK_AUTHOR_ID = createForeignKey(org.jooq.example.migrator.model.v1.Keys.PK_T_AUTHOR, org.jooq.example.migrator.model.v1.tables.v1_BOOK.v1_BOOK, "FK_T_BOOK_AUTHOR_ID", org.jooq.example.migrator.model.v1.tables.v1_BOOK.v1_BOOK.AUTHOR_ID);
    }
}
