/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v1;


import javax.annotation.Generated;

import org.jooq.example.migrator.model.v1.tables.v1_AUTHOR;
import org.jooq.example.migrator.model.v1.tables.v1_BOOK;
import org.jooq.example.migrator.model.v1.tables.v1_schema_version;


/**
 * Convenience access to all tables in FLYWAY_TEST
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:FLYWAY_TEST_1"
    },
    date = "2017-05-03T20:59:30.778Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>FLYWAY_TEST.AUTHOR</code>.
     */
    public static final v1_AUTHOR v1_AUTHOR = org.jooq.example.migrator.model.v1.tables.v1_AUTHOR.v1_AUTHOR;

    /**
     * The table <code>FLYWAY_TEST.BOOK</code>.
     */
    public static final v1_BOOK v1_BOOK = org.jooq.example.migrator.model.v1.tables.v1_BOOK.v1_BOOK;

    /**
     * The table <code>FLYWAY_TEST.schema_version</code>.
     */
    public static final v1_schema_version v1_schema_version = org.jooq.example.migrator.model.v1.tables.v1_schema_version.v1_schema_version;
}
