/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.migrator.model.v1;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.example.migrator.model.v1.tables.v1_Author;
import org.jooq.example.migrator.model.v1.tables.v1_Book;
import org.jooq.example.migrator.model.v1.tables.v1_SchemaVersion;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2",
        "schema version:null"
    },
    date = "2017-05-16T21:33:40.187Z",
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class v1_FlywayTest extends SchemaImpl {

    private static final long serialVersionUID = -1014713744;

    /**
     * The reference instance of <code>FLYWAY_TEST</code>
     */
    public static final v1_FlywayTest v1_FLYWAY_TEST = new v1_FlywayTest();

    /**
     * The table <code>FLYWAY_TEST.AUTHOR</code>.
     */
    public final v1_Author v1_AUTHOR = org.jooq.example.migrator.model.v1.tables.v1_Author.v1_AUTHOR;

    /**
     * The table <code>FLYWAY_TEST.BOOK</code>.
     */
    public final v1_Book v1_BOOK = org.jooq.example.migrator.model.v1.tables.v1_Book.v1_BOOK;

    /**
     * The table <code>FLYWAY_TEST.schema_version</code>.
     */
    public final v1_SchemaVersion v1_SCHEMA_VERSION = org.jooq.example.migrator.model.v1.tables.v1_SchemaVersion.v1_SCHEMA_VERSION;

    /**
     * No further instances allowed
     */
    private v1_FlywayTest() {
        super("FLYWAY_TEST", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.v1_S_AUTHOR_ID);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            v1_Author.v1_AUTHOR,
            v1_Book.v1_BOOK,
            v1_SchemaVersion.v1_SCHEMA_VERSION);
    }
}
